<?php

namespace EmergenceBundle\Repository;

/**
 * ExpAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpAbonnementRepository extends \Doctrine\ORM\EntityRepository
{
}
