<?php

namespace EmergenceBundle\Repository;

/**
 * ExpirerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpirerRepository extends \Doctrine\ORM\EntityRepository
{
}
