<?php

namespace EmergenceBundle\Repository;

/**
 * SituationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationRepository extends \Doctrine\ORM\EntityRepository
{
}
