<?php

namespace EmergenceBundle\Repository;

/**
 * TypePaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
